import { makeStyles, shorthands } from '@fluentui/react-components';

const useStyles = makeStyles({
  container: {
    width: '1100px',
  },
  image: {
    width: '323.41px',
    height: '486px',
    float: 'left',
  },
  content: {
    position: 'relative',
    float: 'left',
    left: '30px',
  },
  movieName: {
    float: 'left',
    height: '49px',
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: '40px',
    lineHeight: '49px',
    textAlign: 'center',
    letterSpacing: '1px',
    textyTransform: 'uppercase',
    color: '#FFFFFF',
    whiteSpace: 'nowrap',
  },
  rating: {
    float: 'left',
    height: '51px',
    width: '51px',
    ...shorthands.borderRadius('50%'),
    ...shorthands.border('1px', 'solid', '#FFFFFF'),
    position: 'relative',
    left: '20px',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsRating: {
    position: 'absolute',
    height: '24px',
    left: '21.67%',
    right: '21.67%',
    top: 'calc(50% - 24px/2)',
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: '20px',
    lineHeight: '24px',
    textAlign: 'center',
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  detailsYearAndTime: {
    width: '323px',
    display: 'block',
    position: 'relative',
    top: '40px',
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: '24px',
    lineHeight: '29px',
    color: '#F65261',
  },
  releaseYear: {
    float: 'left',
  },
  duration: {
    position: 'relative',
    left: '100px',
  },
  detailsDescription: {
    position: 'relative',
    top: '50px',
    width: '698px',
    height: '292px',
    fontFfamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: '20px',
    lineHeight: '24px',
    color: '#FFFFFF',
    mixBlendMode: 'normal',
    opacity: '0.5',
  },
});

export default useStyles;
