import { makeStyles, shorthands } from '@fluentui/react-components';

const useStyles = makeStyles({
  root: {
    ...shorthands.gap('5px'),
    maxWidth: '640px',
    backgroundColor: '#232323',
    ...shorthands.padding('5px'),
    height: '530px',
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
  },
  wrapper: {
    display: 'grid',
    gridTemplateColumns: '350px 260px',
    ...shorthands.gap('20px'),
    '> div': {
      display: 'flex',
      flexDirection: 'column',
      ...shorthands.gap('2px'),
      '> label': {
        fontFamily: 'Montserrat',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: '16px',
        lineHeight: '20px',
        letterSpacing: '0.888889px',
        textTransform: 'uppercase',
        color: '#F65261',
        mixBlendMode: 'normal',
        opacity: '0.8',
      },
      '> span': {
        '> input': {
          height: '28px',
          lineHeight: '24px',
          color: '#FFFFFF',
          backgroundColor: 'rgba(50, 50, 50, 0.948044)',
          mixBlendMode: 'normal',
          opacity: '0.8',
          ...shorthands.borderRadius('4px'),
          '&::placeholder': {
            opacity: '0.3',
          },
        },
        '> select': {
          height: '28px',
          lineHeight: '24px',
          color: '#FFFFFF',
          backgroundColor: 'rgba(50, 50, 50, 0.948044)',
          mixBlendMode: 'normal',
          opacity: '0.8',
          ...shorthands.border('0px'),
          ...shorthands.borderRadius('4px'),
          '&::placeholder': {
            opacity: '0.3',
          },
        },
        '> textarea': {
          height: '200px',
          lineHeight: '24px',
          color: '#FFFFFF',
          backgroundColor: 'rgba(50, 50, 50, 0.948044)',
          mixBlendMode: 'normal',
          opacity: '0.8',
          ...shorthands.border('0px'),
          ...shorthands.borderRadius('4px'),
          '&::placeholder': {
            opacity: '0.3',
          },
        },
      },
    },
  },
  leftColumn: {
    gridColumnStart: '1',
    gridColumnEnd: '1',
  },
  rightColumn: {
    gridColumnStart: '2',
    gridColumnEnd: '2',
  },
  fullColumn: {
    gridColumnStart: '1',
    gridColumnEnd: '3',
  },
  footer: {
    ...shorthands.padding('15px', '10px'),
  },
  footerButtons: {
    float: 'right',
    width: '400px',
  },
  submit: {
    backgroundColor: '#F65261',
    color: 'white',
    float: 'right',
    width: '180px',
    height: '57px',
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '24px',
    ...shorthands.borderRadius('4px'),
  },
  reset: {
    backgroundColor: '#232323',
    color: '#F65261',
    float: 'left',
    width: '180px',
    height: '57px',
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '24px',
    ...shorthands.borderColor('#F65261'),
    ...shorthands.borderRadius('4px'),
  },

  dropDown: {
    minWidth: '150px',
    float: 'right',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '20px',
    letterSpacing: '0.888889px',
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  option: {
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '20px',
    letterSpacing: '0.888889px',
    color: '#FFFFFF',
    backgroundColor: 'black',
    ':hover': {
      backgroundColor: 'black',
    },
  },
  expandIcon: {
    color: '#F65261',
  },
  errorsContainer: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    color: '#F65261',
  },
});

export default useStyles;
